services:
  backend:
    image: 010526287021.dkr.ecr.us-east-1.amazonaws.com/codesnippet/dockerdemoapp:server-latest
    container_name: backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: 010526287021.dkr.ecr.us-east-1.amazonaws.com/codesnippet/dockerdemoapp:client-latest
    container_name: frontend
    ports:
      - "80:80"
    restart: always
